### ISSUE TITLE
Re-using material

### ISSUE THREAD

**Issue by Juke34** [NBISweden/workshop-conda#2]
Hej  @marcelm and @percyfal!  I would be interested in re-using some of your work here (and citing you), would it be possible?
As I didn't see any license I will not without your consent.  
Best regards, Jacques

**Comment by marcelm** [comment]
Speaking for the parts that I authored: Yes, I’d be happy to see it reused!

@percyfal Would CC-BY be fine as license? If you agree, I could add a LICENSE file.

**Comment by percyfal** [comment]
No problem, add away!

**Comment by Juke34** [comment]
Thanks a lot guys, see you soon
